// Arithmetic in GF(2^255 - 19), eight 32-bit limbs, radix 2^32.
//
// GENERATED by cuda/gen_fe32.py -- do not edit the multiply by hand.
//
// ## Why this exists alongside the radix-25.5 implementation
//
// The first implementation used ten signed 25.5-bit limbs accumulated into
// 64-bit registers, following the Ed25519 reference implementation. It is
// easier to get right, because carries are deferred rather than propagated.
// Profiling the search kernel showed the cost of that choice: **56% of the
// kernel's PTX operations were 64-bit** -- 1606 `add.s64`, 1232 `mad.lo.s64`,
// 327 `shr.s64` -- and on this hardware each of those is two 32-bit
// operations. The kernel was spending most of its time synthesising 64-bit
// arithmetic the machine does not have.
//
// This representation uses saturated 32-bit limbs and propagates carries with
// the hardware carry flag, via `mad.lo.cc.u32` / `madc.hi.cc.u32` chains. The
// multiply becomes 64 products in 144 instructions instead of 100 products in
// roughly 590.
//
// ## Representation
//
//     h = h[0] + h[1]*2^32 + h[2]*2^64 + ... + h[7]*2^224
//
// Values are kept below 2^256 and are *not* fully reduced: a value may be
// anywhere in [0, 2^256), and several encodings represent the same field
// element. Canonicalisation happens only in `fe_freeze`, and therefore only in
// `fe_tobytes` and `fe_prefix_be64`. Reduction after each operation folds the
// overflow with the identity 2^256 = 38 (mod 2^255 - 19).
//
// ## The trade against radix 25.5
//
// Addition and subtraction get *more* expensive: they need a real carry chain
// and a fold, where the redundant signed representation could simply add limbs
// and defer. The search kernel does about five multiplications and two
// additions per candidate, so the multiply dominates and the trade pays.

#pragma once

typedef signed char        i8;
typedef unsigned char      u8;
typedef signed int         i32;
typedef unsigned int       u32;
typedef signed long long   i64;
typedef unsigned long long u64;

#define FE_LIMBS 8

// A field element: eight 32-bit limbs, least significant first.
typedef u32 fe[FE_LIMBS];

// The limb type, so code that serialises limbs need not know the layout.
typedef u32 fe_limb;

__device__ __forceinline__ void fe_0(fe h) {
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) h[i] = 0;
}

__device__ __forceinline__ void fe_1(fe h) {
    fe_0(h);
    h[0] = 1;
}

__device__ __forceinline__ void fe_copy(fe h, const fe f) {
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) h[i] = f[i];
}

// Conditional move: h = b ? g : h, branch-free. `b` must be 0 or 1.
__device__ __forceinline__ void fe_cmov(fe h, const fe g, u32 b) {
    const u32 mask = (u32)(-(i32)b);
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) h[i] ^= mask & (h[i] ^ g[i]);
}


// h += k, propagating the carry, and folding any overflow past 2^256 back in
// as another 38. Declared before use by `fe_add` and `fe_mul`.
__device__ __forceinline__ void fe_fold_carry(fe h, u32 k) {
    u32 c;
    asm volatile(
        "add.cc.u32  %0, %0, %9;\n\t"
        "addc.cc.u32 %1, %1, 0;\n\t"
        "addc.cc.u32 %2, %2, 0;\n\t"
        "addc.cc.u32 %3, %3, 0;\n\t"
        "addc.cc.u32 %4, %4, 0;\n\t"
        "addc.cc.u32 %5, %5, 0;\n\t"
        "addc.cc.u32 %6, %6, 0;\n\t"
        "addc.cc.u32 %7, %7, 0;\n\t"
        "addc.u32    %8, 0, 0;\n\t"
        : "+r"(h[0]), "+r"(h[1]), "+r"(h[2]), "+r"(h[3]),
          "+r"(h[4]), "+r"(h[5]), "+r"(h[6]), "+r"(h[7]), "=r"(c)
        : "r"(k));
    // A second carry can only leave the low limb below 38, so this cannot
    // carry again.
    h[0] += c * 38u;
}

// h += k, propagating the carry. Used where the value is known to be below
// 2^255, so the addition cannot overflow 256 bits and needs no fold.
__device__ __forceinline__ void fe_fold_carry_nowrap(fe h, u32 k) {
    asm volatile(
        "add.cc.u32  %0, %0, %8;\n\t"
        "addc.cc.u32 %1, %1, 0;\n\t"
        "addc.cc.u32 %2, %2, 0;\n\t"
        "addc.cc.u32 %3, %3, 0;\n\t"
        "addc.cc.u32 %4, %4, 0;\n\t"
        "addc.cc.u32 %5, %5, 0;\n\t"
        "addc.cc.u32 %6, %6, 0;\n\t"
        "addc.u32    %7, %7, 0;\n\t"
        : "+r"(h[0]), "+r"(h[1]), "+r"(h[2]), "+r"(h[3]),
          "+r"(h[4]), "+r"(h[5]), "+r"(h[6]), "+r"(h[7])
        : "r"(k));
}

// h -= k, propagating the borrow, folding any underflow as another 38.
__device__ __forceinline__ void fe_unfold_borrow(fe h, u32 k) {
    u32 b;
    asm volatile(
        "sub.cc.u32  %0, %0, %9;\n\t"
        "subc.cc.u32 %1, %1, 0;\n\t"
        "subc.cc.u32 %2, %2, 0;\n\t"
        "subc.cc.u32 %3, %3, 0;\n\t"
        "subc.cc.u32 %4, %4, 0;\n\t"
        "subc.cc.u32 %5, %5, 0;\n\t"
        "subc.cc.u32 %6, %6, 0;\n\t"
        "subc.cc.u32 %7, %7, 0;\n\t"
        "subc.u32    %8, 0, 0;\n\t"
        : "+r"(h[0]), "+r"(h[1]), "+r"(h[2]), "+r"(h[3]),
          "+r"(h[4]), "+r"(h[5]), "+r"(h[6]), "+r"(h[7]), "=r"(b)
        : "r"(k));
    h[0] -= b & 38u;
}

// h = f + g (mod 2^255 - 19), result < 2^256.
//
// The sum may carry out of 256 bits; since 2^256 = 38 (mod p), the carry is
// folded back in by adding 38. That addition can itself carry, so it is folded
// once more -- which is enough, because the second carry can only occur when
// the low limbs are saturated and adding 38 again cannot carry a third time.
__device__ __forceinline__ void fe_add(fe h, const fe f, const fe g) {
    u32 c;
    asm volatile(
        "add.cc.u32  %0, %9,  %17;\n\t"
        "addc.cc.u32 %1, %10, %18;\n\t"
        "addc.cc.u32 %2, %11, %19;\n\t"
        "addc.cc.u32 %3, %12, %20;\n\t"
        "addc.cc.u32 %4, %13, %21;\n\t"
        "addc.cc.u32 %5, %14, %22;\n\t"
        "addc.cc.u32 %6, %15, %23;\n\t"
        "addc.cc.u32 %7, %16, %24;\n\t"
        "addc.u32    %8, 0, 0;\n\t"
        : "=r"(h[0]), "=r"(h[1]), "=r"(h[2]), "=r"(h[3]),
          "=r"(h[4]), "=r"(h[5]), "=r"(h[6]), "=r"(h[7]), "=r"(c)
        : "r"(f[0]), "r"(f[1]), "r"(f[2]), "r"(f[3]),
          "r"(f[4]), "r"(f[5]), "r"(f[6]), "r"(f[7]),
          "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]),
          "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    fe_fold_carry(h, c * 38u);
}

// h = f - g (mod 2^255 - 19), result < 2^256.
//
// A borrow means the true result is 2^256 short, so 38 is subtracted to
// compensate, and a second borrow is folded the same way.
__device__ __forceinline__ void fe_sub(fe h, const fe f, const fe g) {
    u32 b;
    asm volatile(
        "sub.cc.u32  %0, %9,  %17;\n\t"
        "subc.cc.u32 %1, %10, %18;\n\t"
        "subc.cc.u32 %2, %11, %19;\n\t"
        "subc.cc.u32 %3, %12, %20;\n\t"
        "subc.cc.u32 %4, %13, %21;\n\t"
        "subc.cc.u32 %5, %14, %22;\n\t"
        "subc.cc.u32 %6, %15, %23;\n\t"
        "subc.cc.u32 %7, %16, %24;\n\t"
        "subc.u32    %8, 0, 0;\n\t"
        : "=r"(h[0]), "=r"(h[1]), "=r"(h[2]), "=r"(h[3]),
          "=r"(h[4]), "=r"(h[5]), "=r"(h[6]), "=r"(h[7]), "=r"(b)
        : "r"(f[0]), "r"(f[1]), "r"(f[2]), "r"(f[3]),
          "r"(f[4]), "r"(f[5]), "r"(f[6]), "r"(f[7]),
          "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]),
          "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // `b` is 0 or 0xffffffff (subc of 0,0 leaves -1 on borrow).
    fe_unfold_borrow(h, b & 38u);
}

__device__ __forceinline__ void fe_neg(fe h, const fe f) {
    fe zero;
    fe_0(zero);
    fe_sub(h, zero, f);
}


// h = f * g (mod 2^255 - 19).
//
// Schoolbook 8x8, one generated asm block per row. Each row runs two carry
// chains: the first accumulates the low halves of that row's eight products,
// the second the high halves, shifted one limb up. 18 instructions per row,
// 144 for the full 512-bit product.
//
// Each row is a single asm block because a carry chain must not be split
// across statements -- the compiler may schedule other instructions between
// them, and the carry flag would not survive.
__device__ __forceinline__ void fe_mul(fe h, const fe f, const fe g) {
    u32 r[17];
#pragma unroll
    for (int i = 0; i < 17; i++) r[i] = 0;
    // row 0
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[0]), "+r"(r[1]), "+r"(r[2]), "+r"(r[3]), "+r"(r[4]), "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9])
        : "r"(f[0]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 1
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[1]), "+r"(r[2]), "+r"(r[3]), "+r"(r[4]), "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10])
        : "r"(f[1]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 2
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[2]), "+r"(r[3]), "+r"(r[4]), "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11])
        : "r"(f[2]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 3
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[3]), "+r"(r[4]), "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11]), "+r"(r[12])
        : "r"(f[3]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 4
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[4]), "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11]), "+r"(r[12]), "+r"(r[13])
        : "r"(f[4]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 5
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[5]), "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11]), "+r"(r[12]), "+r"(r[13]), "+r"(r[14])
        : "r"(f[5]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 6
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[6]), "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11]), "+r"(r[12]), "+r"(r[13]), "+r"(r[14]), "+r"(r[15])
        : "r"(f[6]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));
    // row 7
    asm volatile(
        "mad.lo.cc.u32  %0, %10, %11, %0;\n\t"
        "madc.lo.cc.u32 %1, %10, %12, %1;\n\t"
        "madc.lo.cc.u32 %2, %10, %13, %2;\n\t"
        "madc.lo.cc.u32 %3, %10, %14, %3;\n\t"
        "madc.lo.cc.u32 %4, %10, %15, %4;\n\t"
        "madc.lo.cc.u32 %5, %10, %16, %5;\n\t"
        "madc.lo.cc.u32 %6, %10, %17, %6;\n\t"
        "madc.lo.cc.u32 %7, %10, %18, %7;\n\t"
        "addc.u32       %8, %8, 0;\n\t"
        "mad.hi.cc.u32  %1, %10, %11, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %12, %2;\n\t"
        "madc.hi.cc.u32 %3, %10, %13, %3;\n\t"
        "madc.hi.cc.u32 %4, %10, %14, %4;\n\t"
        "madc.hi.cc.u32 %5, %10, %15, %5;\n\t"
        "madc.hi.cc.u32 %6, %10, %16, %6;\n\t"
        "madc.hi.cc.u32 %7, %10, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %10, %18, %8;\n\t"
        "addc.u32       %9, %9, 0;\n\t"
        : "+r"(r[7]), "+r"(r[8]), "+r"(r[9]), "+r"(r[10]), "+r"(r[11]), "+r"(r[12]), "+r"(r[13]), "+r"(r[14]), "+r"(r[15]), "+r"(r[16])
        : "r"(f[7]), "r"(g[0]), "r"(g[1]), "r"(g[2]), "r"(g[3]), "r"(g[4]), "r"(g[5]), "r"(g[6]), "r"(g[7]));

    // Reduce the 512-bit product. 2^256 = 38 (mod p), so the answer is
    // low(r[0..8]) + 38 * high(r[8..16]).
    u32 c[9];
    asm volatile(
        "mad.lo.cc.u32  %0, %9,  %17, 0;\n\t"
        "madc.lo.cc.u32 %1, %10, %17, 0;\n\t"
        "madc.lo.cc.u32 %2, %11, %17, 0;\n\t"
        "madc.lo.cc.u32 %3, %12, %17, 0;\n\t"
        "madc.lo.cc.u32 %4, %13, %17, 0;\n\t"
        "madc.lo.cc.u32 %5, %14, %17, 0;\n\t"
        "madc.lo.cc.u32 %6, %15, %17, 0;\n\t"
        "madc.lo.cc.u32 %7, %16, %17, 0;\n\t"
        "addc.u32       %8, 0, 0;\n\t"
        "mad.hi.cc.u32  %1, %9,  %17, %1;\n\t"
        "madc.hi.cc.u32 %2, %10, %17, %2;\n\t"
        "madc.hi.cc.u32 %3, %11, %17, %3;\n\t"
        "madc.hi.cc.u32 %4, %12, %17, %4;\n\t"
        "madc.hi.cc.u32 %5, %13, %17, %5;\n\t"
        "madc.hi.cc.u32 %6, %14, %17, %6;\n\t"
        "madc.hi.cc.u32 %7, %15, %17, %7;\n\t"
        "madc.hi.cc.u32 %8, %16, %17, %8;\n\t"
        : "=r"(c[0]), "=r"(c[1]), "=r"(c[2]), "=r"(c[3]), "=r"(c[4]),
          "=r"(c[5]), "=r"(c[6]), "=r"(c[7]), "=r"(c[8])
        : "r"(r[8]), "r"(r[9]), "r"(r[10]), "r"(r[11]), "r"(r[12]),
          "r"(r[13]), "r"(r[14]), "r"(r[15]), "n"(38));

    u32 top;
    asm volatile(
        "add.cc.u32  %0, %9,  %17;\n\t"
        "addc.cc.u32 %1, %10, %18;\n\t"
        "addc.cc.u32 %2, %11, %19;\n\t"
        "addc.cc.u32 %3, %12, %20;\n\t"
        "addc.cc.u32 %4, %13, %21;\n\t"
        "addc.cc.u32 %5, %14, %22;\n\t"
        "addc.cc.u32 %6, %15, %23;\n\t"
        "addc.cc.u32 %7, %16, %24;\n\t"
        "addc.u32    %8, %25, 0;\n\t"
        : "=r"(h[0]), "=r"(h[1]), "=r"(h[2]), "=r"(h[3]),
          "=r"(h[4]), "=r"(h[5]), "=r"(h[6]), "=r"(h[7]), "=r"(top)
        : "r"(r[0]), "r"(r[1]), "r"(r[2]), "r"(r[3]),
          "r"(r[4]), "r"(r[5]), "r"(r[6]), "r"(r[7]),
          "r"(c[0]), "r"(c[1]), "r"(c[2]), "r"(c[3]),
          "r"(c[4]), "r"(c[5]), "r"(c[6]), "r"(c[7]), "r"(c[8]));

    // `top` counts multiples of 2^256 still outstanding; fold them in as 38
    // each. `top` is small (below 2^6), so 38*top cannot overflow a limb.
    fe_fold_carry(h, top * 38u);
}

// h = f * f. Squaring admits a symmetry optimisation, but it is used almost
// only inside the exponentiation ladder, whose cost is amortised across a whole
// batch by Montgomery's trick.
__device__ __forceinline__ void fe_sq(fe h, const fe f) { fe_mul(h, f, f); }


// Load from 32 little-endian bytes. Bit 255 is masked off here, not by the
// caller: a compressed point carries the x sign there, and admitting it would
// silently accept values with no canonical representation.
__device__ __forceinline__ void fe_frombytes(fe h, const u8 *s) {
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) {
        h[i] = (u32)s[4 * i] | ((u32)s[4 * i + 1] << 8)
             | ((u32)s[4 * i + 2] << 16) | ((u32)s[4 * i + 3] << 24);
    }
    h[7] &= 0x7fffffffu;
}

// Reduce to the canonical representative in [0, p).
//
// Done in two stages rather than by repeated conditional subtraction, because
// the input can exceed 2p and a single subtract-if-greater is then not enough.
//
//   1. Fold bit 255 down: 2^255 = 19 (mod p), so clearing that bit and adding
//      19 in its place leaves the value below 2^255 + 19.
//   2. That is at most p + 37, so exactly one conditional subtraction of p
//      finishes the job. Subtracting p is adding 19 and clearing bit 255, and
//      "is it at least p" is precisely "does adding 19 reach 2^255".
//
// Both steps are constant-time selects rather than branches.
__device__ __forceinline__ void fe_freeze(fe t, const fe h) {
    fe_copy(t, h);

    // Stage 1: fold bit 255.
    const u32 top = t[7] >> 31;
    t[7] &= 0x7fffffffu;
    fe_fold_carry_nowrap(t, top * 19u);

    // Stage 2: q = t + 19; t >= p exactly when bit 255 of q is set.
    u32 q[FE_LIMBS];
    asm volatile(
        "add.cc.u32  %0, %8,  %16;\n\t"
        "addc.cc.u32 %1, %9,  0;\n\t"
        "addc.cc.u32 %2, %10, 0;\n\t"
        "addc.cc.u32 %3, %11, 0;\n\t"
        "addc.cc.u32 %4, %12, 0;\n\t"
        "addc.cc.u32 %5, %13, 0;\n\t"
        "addc.cc.u32 %6, %14, 0;\n\t"
        "addc.u32    %7, %15, 0;\n\t"
        : "=r"(q[0]), "=r"(q[1]), "=r"(q[2]), "=r"(q[3]),
          "=r"(q[4]), "=r"(q[5]), "=r"(q[6]), "=r"(q[7])
        : "r"(t[0]), "r"(t[1]), "r"(t[2]), "r"(t[3]),
          "r"(t[4]), "r"(t[5]), "r"(t[6]), "r"(t[7]), "n"(19));

    const u32 mask = (u32)(-(i32)(q[7] >> 31));
    q[7] &= 0x7fffffffu;
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) t[i] = (t[i] & ~mask) | (q[i] & mask);
}

// Store as 32 little-endian bytes, fully reduced.
__device__ __forceinline__ void fe_tobytes(u8 *s, const fe h) {
    fe t;
    fe_freeze(t, h);
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) {
        s[4 * i]     = (u8)(t[i]);
        s[4 * i + 1] = (u8)(t[i] >> 8);
        s[4 * i + 2] = (u8)(t[i] >> 16);
        s[4 * i + 3] = (u8)(t[i] >> 24);
    }
}

// The first eight bytes of the canonical encoding, read big-endian: the
// prefilter probe. Limbs 0 and 1 are exactly bytes 0..7, so no bit shuffling is
// needed at all -- the saturated representation lines up with byte boundaries,
// which the radix-25.5 one did not.
__device__ __forceinline__ u64 fe_prefix_be64(const fe h) {
    fe t;
    fe_freeze(t, h);
    const u32 lo = t[0], hi = t[1];
    // Byte-reverse the 64-bit little-endian value; the compiler lowers each
    // 32-bit reversal to a single PRMT.
    const u32 a = __byte_perm(lo, 0, 0x0123);
    const u32 b = __byte_perm(hi, 0, 0x0123);
    return ((u64)a << 32) | (u64)b;
}

__device__ __forceinline__ u32 fe_isnonzero(const fe f) {
    fe t;
    fe_freeze(t, f);
    u32 acc = 0;
#pragma unroll
    for (int i = 0; i < FE_LIMBS; i++) acc |= t[i];
    return acc != 0;
}

__device__ __forceinline__ u32 fe_isnegative(const fe f) {
    fe t;
    fe_freeze(t, f);
    return t[0] & 1u;
}

// out = z^(2^252 - 3). Shared skeleton for inversion and square roots.
__device__ __noinline__ void fe_pow22523(fe out, const fe z) {
    fe t0, t1, t2;
    int i;
    fe_sq(t0, z);
    fe_sq(t1, t0); fe_sq(t1, t1);
    fe_mul(t1, z, t1);
    fe_mul(t0, t0, t1);
    fe_sq(t0, t0);
    fe_mul(t0, t1, t0);
    fe_sq(t1, t0); for (i = 1; i < 5; i++) fe_sq(t1, t1);
    fe_mul(t0, t1, t0);
    fe_sq(t1, t0); for (i = 1; i < 10; i++) fe_sq(t1, t1);
    fe_mul(t1, t1, t0);
    fe_sq(t2, t1); for (i = 1; i < 20; i++) fe_sq(t2, t2);
    fe_mul(t1, t2, t1);
    fe_sq(t1, t1); for (i = 1; i < 10; i++) fe_sq(t1, t1);
    fe_mul(t0, t1, t0);
    fe_sq(t1, t0); for (i = 1; i < 50; i++) fe_sq(t1, t1);
    fe_mul(t1, t1, t0);
    fe_sq(t2, t1); for (i = 1; i < 100; i++) fe_sq(t2, t2);
    fe_mul(t1, t2, t1);
    fe_sq(t1, t1); for (i = 1; i < 50; i++) fe_sq(t1, t1);
    fe_mul(t0, t1, t0);
    fe_sq(t0, t0); fe_sq(t0, t0);
    fe_mul(out, t0, z);
}

// out = 1/z, by Fermat: z^(p-2). 1/0 evaluates to 0.
__device__ __noinline__ void fe_invert(fe out, const fe z) {
    fe t0, t1, t2, t3;
    int i;
    fe_sq(t0, z);
    fe_sq(t1, t0); fe_sq(t1, t1);
    fe_mul(t1, z, t1);
    fe_mul(t0, t0, t1);
    fe_sq(t2, t0);
    fe_mul(t1, t1, t2);
    fe_sq(t2, t1); for (i = 1; i < 5; i++) fe_sq(t2, t2);
    fe_mul(t1, t2, t1);
    fe_sq(t2, t1); for (i = 1; i < 10; i++) fe_sq(t2, t2);
    fe_mul(t2, t2, t1);
    fe_sq(t3, t2); for (i = 1; i < 20; i++) fe_sq(t3, t3);
    fe_mul(t2, t3, t2);
    fe_sq(t2, t2); for (i = 1; i < 10; i++) fe_sq(t2, t2);
    fe_mul(t1, t2, t1);
    fe_sq(t2, t1); for (i = 1; i < 50; i++) fe_sq(t2, t2);
    fe_mul(t2, t2, t1);
    fe_sq(t3, t2); for (i = 1; i < 100; i++) fe_sq(t3, t3);
    fe_mul(t2, t3, t2);
    fe_sq(t2, t2); for (i = 1; i < 50; i++) fe_sq(t2, t2);
    fe_mul(t1, t2, t1);
    fe_sq(t1, t1); for (i = 1; i < 5; i++) fe_sq(t1, t1);
    fe_mul(out, t1, t0);
}

