// Group arithmetic on the Ed25519 curve, and the incremental walk that makes
// vanity search cheap.
//
// ## The idea
//
// A naive search generates a random secret scalar, multiplies the base point by
// it, and checks the resulting address. Scalar multiplication costs roughly 250
// point operations, which caps throughput far below what the hardware can do.
//
// Ed25519 clamping clears the low three bits of every secret scalar, so every
// valid scalar is a multiple of 8. Therefore, starting from any valid scalar a
// and its public point A = a*B, the sequence
//
//     a_k = a + 8k          A_k = A_{k-1} + 8B
//
// visits valid scalars using a single point *addition* per candidate. Since 8B
// is a compile-time constant available in precomputed affine form, that
// addition is a "mixed" addition costing eight field multiplications rather
// than the ~2000 a scalar multiplication would need.
//
// The host knows a and receives k, so it can reconstruct the secret as a + 8k
// without the device ever holding secret material. See
// `docs/05-security-model.md`.
//
// ## Coordinates
//
// Points are kept in extended coordinates (X:Y:Z:T) with x = X/Z, y = Y/Z and
// XY = ZT, which makes addition inversion-free. Recovering the affine y needed
// for an address costs one modular inversion — far more than the addition
// itself — so inversions are batched; see `fe_batch_invert_step` and the
// comment on Montgomery's trick in search.cu.

#pragma once

#if FE_RADIX32
#include "fe25519_u32.cuh"
#else
#include "fe25519.cuh"
#endif

// Extended coordinates: x = X/Z, y = Y/Z, T = XY/Z.
struct ge_p3 {
    fe X, Y, Z, T;
};

// The output of a mixed addition: x = X/Z, y = Y/T. Cheaper to produce than a
// p3 and converted only when the next addition needs it.
struct ge_p1p1 {
    fe X, Y, Z, T;
};

// An affine point in "niels" form, precomputed for use as the second operand of
// a mixed addition.
struct ge_precomp {
    fe yplusx, yminusx, xy2d;
};

// GENERATED by cuda/gen_constants.py -- do not edit by hand.
// 8*B compresses to: b4b937fca95b2f1e93e41e62fc3c78818ff38a66096fad6e7973e5c90006d321

// d = -121665/121666, the Edwards curve parameter
#if FE_RADIX32
__device__ __constant__ const fe fe_d = {324630691, 1978355146, 1094834347, 7342669, 2004478104, 2361868409, 728759923, 1375956206};
#else
__device__ __constant__ const fe fe_d = {56195235, 13857412, 51736253, 6949390, 114729, 24766616, 60832955, 30306712, 48412415, 21499315};
#endif

// sqrt(-1), used to pick the branch when decompressing
#if FE_RADIX32
__device__ __constant__ const fe fe_sqrtm1 = {1242472624, 3303938855, 2905597048, 792926214, 1039914919, 726466713, 1338105611, 730014848};
#else
__device__ __constant__ const fe fe_sqrtm1 = {34513072, 25610706, 9377949, 3500415, 12389472, 33281959, 41962654, 31548777, 326685, 11406482};
#endif

// 8*B in affine form. The offset table is built by walking from here.
//   x
#if FE_RADIX32
__device__ __constant__ const fe ge_8b_x = {145065160, 998768060, 2154400665, 3946497659, 4165914515, 1116089692, 2547478966, 1732436319};
#else
__device__ __constant__ const fe ge_8b_x = {10847432, 33517314, 24323952, 31195980, 61664025, 5164947, 51818108, 3590224, 33127799, 27069317};
#endif

//   y
#if FE_RADIX32
__device__ __constant__ const fe ge_8b_y = {4231510452, 506420137, 1646191763, 2172140796, 1720382351, 1856859913, 3387257721, 567477760};
#else
__device__ __constant__ const fe ge_8b_y = {3652020, 30861951, 9593797, 31658231, 33939699, 9106319, 45581491, 7286229, 826967, 8866840};
#endif

// 8*B in 'niels' form: the precomputed operand of a mixed addition.
//   y + x
#if FE_RADIX32
__device__ __constant__ const fe ge_8b_yplusx = {81608335, 1505188198, 3800592428, 1823671159, 1591329571, 2972949606, 1639769391, 152430432};
#else
__device__ __constant__ const fe ge_8b_yplusx = {14499471, 30824833, 33917750, 29299779, 28494861, 14271267, 30290735, 10876454, 33954766, 2381725};
#endif

//   y - x
#if FE_RADIX32
__device__ __constant__ const fe ge_8b_yminusx = {4086445273, 3802619373, 3786758393, 2520610432, 1849435131, 740770220, 839778755, 982525089};
#else
__device__ __constant__ const fe ge_8b_yminusx = {59913433, 30899068, 52378708, 462250, 39384538, 3941371, 60872247, 3696004, 34808032, 15351954};
#endif

//   2*d*x*y
#if FE_RADIX32
__device__ __constant__ const fe ge_8b_xy2d = {3382874394, 3888248281, 2345445335, 3097719160, 246819378, 1667502617, 785141397, 647003228};
#else
__device__ __constant__ const fe ge_8b_xy2d = {27431194, 8222322, 16448760, 29646437, 48401861, 11938354, 34147463, 30583916, 29551812, 10109425};
#endif


// r = p + q, where q is an affine point in niels form.
//
// This is the "madd" formula for extended twisted Edwards coordinates with
// a = -1. Eight field multiplications in total: four here and four in
// ge_p1p1_to_p3.
__device__ __forceinline__ void ge_madd(ge_p1p1 *r, const ge_p3 *p,
                                        const ge_precomp *q) {
    fe t0;
    fe_add(r->X, p->Y, p->X);        // A = Y1 + X1
    fe_sub(r->Y, p->Y, p->X);        // B = Y1 - X1
    fe_mul(r->Z, r->X, q->yplusx);   // C = A * (y2 + x2)
    fe_mul(r->Y, r->Y, q->yminusx);  // D = B * (y2 - x2)
    fe_mul(r->T, q->xy2d, p->T);     // E = T1 * 2*d*x2*y2
    fe_add(t0, p->Z, p->Z);          // F = 2*Z1
    fe_sub(r->X, r->Z, r->Y);        // X3 = C - D
    fe_add(r->Y, r->Z, r->Y);        // Y3 = C + D
    fe_add(r->Z, t0, r->T);          // Z3 = F + E
    fe_sub(r->T, t0, r->T);          // T3 = F - E
}

// Convert a p1p1 back to extended coordinates. Four multiplications.
__device__ __forceinline__ void ge_p1p1_to_p3(ge_p3 *r, const ge_p1p1 *p) {
    fe_mul(r->X, p->X, p->T);
    fe_mul(r->Y, p->Y, p->Z);
    fe_mul(r->Z, p->Z, p->T);
    fe_mul(r->T, p->X, p->Y);
}

// The niels form of 8*B, assembled from the generated constants above.
__device__ __forceinline__ void ge_precomp_8b(ge_precomp *q) {
    fe_copy(q->yplusx, ge_8b_yplusx);
    fe_copy(q->yminusx, ge_8b_yminusx);
    fe_copy(q->xy2d, ge_8b_xy2d);
}

// p += 8*B, in place.
__device__ __forceinline__ void ge_add_8b(ge_p3 *p) {
    ge_precomp q;
    ge_precomp_8b(&q);
    ge_p1p1 t;
    ge_madd(&t, p, &q);
    ge_p1p1_to_p3(p, &t);
}

// Compress a point to the 32-byte encoding an Ed25519 public key uses: the
// affine y, little-endian, with the low bit of the affine x in bit 255.
//
// Costs a modular inversion, so the search kernel does *not* call this per
// candidate; it batches the inversions instead. Provided for setup, tests, and
// the rare reporting path.
__device__ __noinline__ void ge_p3_tobytes(u8 *s, const ge_p3 *p) {
    fe recip, x, y;
    fe_invert(recip, p->Z);
    fe_mul(x, p->X, recip);
    fe_mul(y, p->Y, recip);
    fe_tobytes(s, y);
    s[31] ^= (u8)(fe_isnegative(x) << 7);
}

// Decompress a 32-byte public key into extended coordinates.
//
// Returns 1 on success, 0 when the encoding does not name a curve point. The
// caller must check: a search thread whose starting point failed to decompress
// would otherwise walk a sequence of meaningless values at full speed and
// report nothing, which is indistinguishable from bad luck. Failure here means
// the host sent something that is not a public key, so it is a bug, and the
// kernel reports it rather than absorbing it.
//
// The square root is computed as (u/v)^((p+3)/8) via the identity
// x = u v^3 (u v^7)^((p-5)/8), which needs one exponentiation rather than two.
// When that root is off by a factor of sqrt(-1) — which happens for half of all
// inputs — it is corrected by multiplying it back in.
__device__ __noinline__ u32 ge_frombytes(ge_p3 *h, const u8 *s) {
    fe u, v, v3, vxx, check;

    fe_frombytes(h->Y, s);
    fe_1(h->Z);
    fe_sq(u, h->Y);
    fe_mul(v, u, fe_d);
    fe_sub(u, u, h->Z);   // u = y^2 - 1
    fe_add(v, v, h->Z);   // v = d*y^2 + 1

    fe_sq(v3, v);
    fe_mul(v3, v3, v);    // v^3
    fe_sq(h->X, v3);
    fe_mul(h->X, h->X, v);
    fe_mul(h->X, h->X, u); // u * v^7

    fe_pow22523(h->X, h->X);
    fe_mul(h->X, h->X, v3);
    fe_mul(h->X, h->X, u); // x = u * v^3 * (u * v^7)^((p-5)/8)

    fe_sq(vxx, h->X);
    fe_mul(vxx, vxx, v);
    fe_sub(check, vxx, u); // v*x^2 - u
    if (fe_isnonzero(check)) {
        fe_add(check, vxx, u); // v*x^2 + u
        if (fe_isnonzero(check)) {
            return 0; // u/v is not a square: not a point
        }
        fe_mul(h->X, h->X, fe_sqrtm1);
    }

    // Match the sign bit the encoding asked for.
    if (fe_isnegative(h->X) != (u32)(s[31] >> 7)) {
        fe_neg(h->X, h->X);
    }
    fe_mul(h->T, h->X, h->Y);
    return 1;
}

// Whether a point satisfies the curve equation -x^2 + y^2 = 1 + d*x^2*y^2.
//
// Used by the tests and by the kernel's optional self-check. A point that
// drifts off the curve is the signature of a field-arithmetic bug or a memory
// fault, and is worth detecting explicitly rather than inferring from a search
// that mysteriously never succeeds.
__device__ __noinline__ u32 ge_p3_is_on_curve(const ge_p3 *p) {
    fe recip, x, y, x2, y2, lhs, rhs, t;
    fe_invert(recip, p->Z);
    fe_mul(x, p->X, recip);
    fe_mul(y, p->Y, recip);
    fe_sq(x2, x);
    fe_sq(y2, y);
    fe_sub(lhs, y2, x2);          // y^2 - x^2
    fe_mul(t, x2, y2);
    fe_mul(rhs, t, fe_d);
    fe_1(t);
    fe_add(rhs, rhs, t);          // 1 + d*x^2*y^2
    fe_sub(t, lhs, rhs);
    return fe_isnonzero(t) ? 0u : 1u;
}

// ---------------------------------------------------------------------------
// The dual addition law
// ---------------------------------------------------------------------------
//
// For a twisted Edwards curve with a = -1, the y coordinate of a sum can be
// written without reference to the curve constant d, and without ever forming
// projective coordinates for the result:
//
//     y(P + Q) = (x1*y1 - x2*y2) / (x1*y2 - y1*x2)
//     y(P - Q) = (x1*y1 + x2*y2) / (x1*y2 + y1*x2)
//
// (Verified against the standard addition law in `cuda/verify_dual_law.py`.)
//
// Two properties make this the right formula for a vanity search:
//
//   * Only y is produced, which is all an address needs — the x coordinate
//     costs nothing because it is never computed.
//   * The two results share the products `x1*y2` and `y1*x2`, differing only in
//     an addition versus a subtraction. Two candidates for the price of two
//     multiplications.
//
// The results are fractions. Since a batch inversion is required anyway, the
// numerator and denominator are carried separately and the division happens
// once for the whole batch — so the "division" in the formulas above is free.
//
// See docs/01-ed25519-vanity-search.md.

// An affine point, with its x*y product precomputed.
//
// `xy` is what makes the dual law cheap: it is the term that distinguishes
// P+Q from P-Q, and precomputing it for the fixed offsets means the moving
// point contributes only two multiplications per pair of candidates.
struct ge_affine {
    fe x, y, xy;
};

// Numerator and denominator of a candidate's y coordinate.
struct ge_yfrac {
    fe num, den;
};

// The y coordinates of `base + off` and `base - off`, as unreduced fractions.
//
// Costs exactly two multiplications for both results.
__device__ __forceinline__ void ge_dual_pair(ge_yfrac *plus, ge_yfrac *minus,
                                             const ge_affine *base,
                                             const fe off_x, const fe off_y,
                                             const fe off_xy) {
    fe x1y2, y1x2;
    fe_mul(x1y2, base->x, off_y);   // x1 * y2
    fe_mul(y1x2, base->y, off_x);   // y1 * x2

    fe_sub(plus->num, base->xy, off_xy);   // x1*y1 - x2*y2
    fe_sub(plus->den, x1y2, y1x2);         // x1*y2 - y1*x2
    fe_add(minus->num, base->xy, off_xy);  // x1*y1 + x2*y2
    fe_add(minus->den, x1y2, y1x2);        // x1*y2 + y1*x2
}

// Affine form of an extended-coordinate point, given 1/Z.
__device__ __forceinline__ void ge_p3_to_affine(ge_affine *a, const ge_p3 *p,
                                                const fe zinv) {
    fe_mul(a->x, p->X, zinv);
    fe_mul(a->y, p->Y, zinv);
    fe_mul(a->xy, a->x, a->y);
}

// 8*B as an extended-coordinate point, from the generated affine constants.
__device__ __forceinline__ void ge_p3_8b(ge_p3 *p) {
    fe_copy(p->X, ge_8b_x);
    fe_copy(p->Y, ge_8b_y);
    fe_1(p->Z);
    fe_mul(p->T, ge_8b_x, ge_8b_y);
}

// Convert an affine point to niels form, so it can be the second operand of a
// mixed addition.
__device__ __forceinline__ void ge_affine_to_precomp(ge_precomp *q, const fe x,
                                                     const fe y) {
    fe t;
    fe_add(q->yplusx, y, x);
    fe_sub(q->yminusx, y, x);
    fe_mul(t, x, y);
    fe_mul(t, t, fe_d);
    fe_add(q->xy2d, t, t);   // 2*d*x*y
}
