#!/usr/bin/env python3
"""Generate the curve constants embedded in ge25519.cuh.

Run:  python3 cuda/gen_constants.py

The output is checked in as part of ge25519.cuh. It is regenerated rather than
hand-written because a mistyped limb is invisible to inspection and fatal in
effect. The values produced here are cross-checked against curve25519-dalek by
`crates/honion-gpu/tests/group_arithmetic.rs`, which recompresses 8*B and
compares; if this script were wrong, that test fails.
"""

P = 2**255 - 19
D = (-121665 * pow(121666, P - 2, P)) % P


def recover_x(y: int, sign: int) -> int:
    """The x coordinate on the Edwards curve -x^2 + y^2 = 1 + d x^2 y^2."""
    xx = (y * y - 1) * pow(D * y * y + 1, P - 2, P) % P
    x = pow(xx, (P + 3) // 8, P)
    if (x * x - xx) % P != 0:
        x = x * pow(2, (P - 1) // 4, P) % P
    assert (x * x - xx) % P == 0, "point is not on the curve"
    if x % 2 != sign:
        x = P - x
    return x


BY = 4 * pow(5, P - 2, P) % P
BX = recover_x(BY, 0)


def add(p1, p2):
    x1, y1 = p1
    x2, y2 = p2
    k = D * x1 * x2 * y1 * y2 % P
    x3 = (x1 * y2 + x2 * y1) * pow(1 + k, P - 2, P) % P
    y3 = (y1 * y2 + x1 * x2) * pow(1 - k, P - 2, P) % P
    return (x3, y3)


def mul(point, n):
    result = (0, 1)  # the identity
    addend = point
    while n:
        if n & 1:
            result = add(result, addend)
        addend = add(addend, addend)
        n >>= 1
    return result


def on_curve(pt) -> bool:
    x, y = pt
    return (-x * x + y * y - 1 - D * x * x * y * y) % P == 0


LIMB_BITS = [26, 25, 26, 25, 26, 25, 26, 25, 26, 25]


def limbs_r255(v: int) -> list[int]:
    """Decompose into the radix-25.5 representation used by fe25519.cuh."""
    v %= P
    out = []
    for w in LIMB_BITS:
        out.append(v & ((1 << w) - 1))
        v >>= w
    assert v == 0, "value did not fit in 255 bits"
    return out


def limbs_u32(v: int) -> list[int]:
    """Decompose into the eight 32-bit limbs used by fe25519_u32.cuh."""
    v %= P
    return [(v >> (32 * i)) & 0xFFFFFFFF for i in range(8)]


def emit(name: str, v: int, comment: str) -> str:
    """Emit the constant for whichever limb layout is compiled in."""
    a = ", ".join(str(x) for x in limbs_u32(v))
    b = ", ".join(str(x) for x in limbs_r255(v))
    return (f"// {comment}\n"
            f"#if FE_RADIX32\n"
            f"__device__ __constant__ const fe {name} = {{{a}}};\n"
            f"#else\n"
            f"__device__ __constant__ const fe {name} = {{{b}}};\n"
            f"#endif\n")


def compress(pt) -> bytes:
    x, y = pt
    return (y | ((x & 1) << 255)).to_bytes(32, "little")


if __name__ == "__main__":
    B = (BX, BY)
    assert on_curve(B), "base point off curve"
    B8 = mul(B, 8)
    assert on_curve(B8), "8B off curve"

    x8, y8 = B8
    print("// GENERATED by cuda/gen_constants.py -- do not edit by hand.")
    print(f"// 8*B compresses to: {compress(B8).hex()}")
    print()
    print(emit("fe_d", D, "d = -121665/121666, the Edwards curve parameter"))
    print(emit("fe_sqrtm1", pow(2, (P - 1) // 4, P), "sqrt(-1), used to pick the branch when decompressing"))
    print("// 8*B in affine form. The offset table is built by walking from here.")
    print(emit("ge_8b_x", x8, "  x"))
    print(emit("ge_8b_y", y8, "  y"))
    print("// 8*B in 'niels' form: the precomputed operand of a mixed addition.")
    print(emit("ge_8b_yplusx", (y8 + x8) % P, "  y + x"))
    print(emit("ge_8b_yminusx", (y8 - x8) % P, "  y - x"))
    print(emit("ge_8b_xy2d", (2 * D * x8 * y8) % P, "  2*d*x*y"))
