//! Compiling device code at run time.
//!
//! # Why run-time compilation
//!
//! The obvious build strategy is to invoke `nvcc` from `build.rs` and embed the
//! resulting cubin. That is not viable here: CUDA 13.1's headers declare
//! `rsqrt`/`rsqrtf` without exception specifications, which collides with the
//! C23 declarations glibc 2.42 added, and the collision aborts *every* `nvcc`
//! invocation — even `--ptx`, which needs no host compiler at all.
//!
//! NVRTC compiles device code in process and never includes a host header, so
//! the conflict cannot arise. Three further benefits follow:
//!
//! * The build needs no CUDA toolkit, only the driver and `libnvrtc` at run
//!   time. Users do not have to install a 4 GB toolkit to run a search.
//! * The target architecture is chosen from the GPU actually present rather
//!   than guessed at build time.
//! * Search parameters that are constant for a given run — batch size, the
//!   number of mask groups — can be compiled *into* the kernel as literals,
//!   which lets the compiler unroll and specialise. See
//!   [`KernelSpec`](crate::kernel::KernelSpec).
//!
//! # The source tree is embedded, not read from disk
//!
//! Device sources are pulled in with `include_str!` at build time. A binary
//! therefore carries the exact kernel it was built with, and cannot be made to
//! compile something else by changing files next to it — the device source is
//! not an input the program parses at run time (langsec rule 4).

use std::collections::BTreeMap;
use std::hash::{DefaultHasher, Hash, Hasher};
use std::path::PathBuf;
use std::sync::Mutex;

/// The device sources, embedded at build time.
pub mod sources {
    /// Field arithmetic in GF(2^255 - 19), ten 25.5-bit limbs.
    pub const FE25519: &str = include_str!("../../../cuda/fe25519.cuh");
    /// Field arithmetic in GF(2^255 - 19), eight 32-bit limbs with hardware
    /// carry chains. Generated by `cuda/gen_fe32.py`.
    pub const FE25519_U32: &str = include_str!("../../../cuda/fe25519_u32.cuh");
    /// Group arithmetic on the Edwards curve.
    pub const GE25519: &str = include_str!("../../../cuda/ge25519.cuh");
    /// Test-only kernels exercising individual primitives.
    pub const TESTKERNELS: &str = include_str!("../../../cuda/testkernels.cu");
    /// The vanity search kernel.
    pub const SEARCH: &str = include_str!("../../../cuda/search.cu");
}

/// The headers that `#include "..."` may name.
///
/// A closed list, deliberately: an include that is not here is an error, so the
/// set of text that can reach the device compiler is fixed at build time and
/// cannot be widened by anything the program reads at run time.
fn known_headers() -> BTreeMap<&'static str, &'static str> {
    [
        ("fe25519.cuh", sources::FE25519),
        ("fe25519_u32.cuh", sources::FE25519_U32),
        ("ge25519.cuh", sources::GE25519),
    ]
    .into_iter()
    .collect()
}

/// Resolve `#include "..."` directives against the embedded sources.
///
/// NVRTC can be handed headers as named buffers, but doing the substitution
/// here keeps the include graph explicit and finite. Each header is emitted at
/// most once across the whole expansion — the effect `#pragma once` has in a
/// real preprocessor, which NVRTC does not apply to buffers we paste together
/// ourselves. `seen` is threaded through the recursion rather than recreated
/// per call, which is what makes that guarantee hold for diamond includes: both
/// `testkernels.cu` and `ge25519.cuh` include `fe25519.cuh`, and emitting it
/// twice is a compile error, not a silent duplicate.
fn expand_into(
    source: &str,
    seen: &mut Vec<&'static str>,
    out: &mut String,
) -> Result<(), NvrtcError> {
    let known = known_headers();
    for line in source.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix("#include \"") else {
            out.push_str(line);
            out.push('\n');
            continue;
        };
        let Some(name) = rest.split('"').next() else {
            return Err(NvrtcError::MalformedInclude {
                line: line.to_owned(),
            });
        };
        let Some((canonical, body)) = known.get_key_value(name) else {
            return Err(NvrtcError::UnknownInclude {
                name: name.to_owned(),
            });
        };
        if seen.contains(canonical) {
            continue;
        }
        seen.push(canonical);
        expand_into(body, seen, out)?;
    }
    Ok(())
}

/// Expand includes and return the result, for tools that need to map compiler
/// line numbers back to source.
///
/// # Errors
///
/// As [`compile`].
pub fn expand_for_debug(source: &str) -> Result<String, NvrtcError> {
    expand_includes(source)
}

/// Expand every include in `source`, emitting each header at most once.
fn expand_includes(source: &str) -> Result<String, NvrtcError> {
    let mut seen: Vec<&'static str> = Vec::new();
    let mut out = String::with_capacity(source.len() * 3);
    expand_into(source, &mut seen, &mut out)?;
    Ok(out)
}

/// Compile device source to PTX for the given compute capability.
///
/// `arch` is a compute capability as `(major, minor)`, e.g. `(12, 0)` for the
/// Blackwell RTX PRO 6000.
///
/// # Errors
///
/// Returns the compiler log on failure, which is the only useful diagnostic
/// NVRTC provides.
pub fn compile(source: &str, arch: (u32, u32), defines: &[(&str, String)]) -> Result<String, NvrtcError> {
    compile_with_options(source, arch, defines, &[])
}

/// Compile with extra NVRTC options appended.
///
/// Used by the instruction-attribution tool, which needs `--generate-line-info`
/// to map PTX back to the source lines that emitted it. Kept separate so the
/// normal path cannot accidentally pick up debug options.
///
/// # Errors
///
/// As [`compile`].
pub fn compile_with_options(
    source: &str,
    arch: (u32, u32),
    defines: &[(&str, String)],
    extra: &[String],
) -> Result<String, NvrtcError> {
    let expanded = expand_includes(source)?;

    let mut opts: Vec<String> = vec![
        format!("--gpu-architecture=compute_{}{}", arch.0, arch.1),
        // Treat every function as `__device__` unless marked otherwise, so the
        // headers need no host/device annotations they would not otherwise
        // carry.
        "-default-device".to_owned(),
        "--std=c++17".to_owned(),
        // Fused multiply-add reassociation is irrelevant to integer code but
        // disabling it removes a source of surprise if float ever creeps in.
        "--fmad=false".to_owned(),
    ];
    for (name, value) in defines {
        opts.push(format!("-D{name}={value}"));
    }
    opts.extend(extra.iter().cloned());

    let opt_refs: Vec<&str> = opts.iter().map(String::as_str).collect();
    let ptx = cudarc::nvrtc::safe::compile_ptx_with_opts(
        &expanded,
        cudarc::nvrtc::safe::CompileOptions {
            options: opt_refs.iter().map(|s| (*s).to_owned()).collect(),
            ..Default::default()
        },
    )
    .map_err(|e| NvrtcError::Compile {
        message: format!("{e:?}"),
    })?;

    Ok(ptx.to_src())
}

/// Process-wide cache so repeated compiles of identical source are free.
static CACHE: Mutex<Option<BTreeMap<String, String>>> = Mutex::new(None);

/// Where compiled PTX is cached between runs.
///
/// Compiling the search kernel takes about four seconds, which is a real cost
/// for a tool people run repeatedly — and on a 90-second benchmark it is 4.7%
/// of the whole measurement. The cache key covers the full expanded source, the
/// target architecture and every define, so a changed kernel or a different GPU
/// simply misses rather than returning something stale.
fn disk_cache_path(key: u64) -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))?;
    Some(base.join("honion").join(format!("{key:016x}.ptx")))
}

/// Hash of everything that determines the compiled output.
fn cache_key(source: &str, arch: (u32, u32), defines: &[(&str, String)]) -> u64 {
    let mut h = DefaultHasher::new();
    source.hash(&mut h);
    arch.hash(&mut h);
    defines.hash(&mut h);
    // Bump when the compile options below change in a way the source does not
    // capture, so old entries are not reused.
    "v1".hash(&mut h);
    h.finish()
}

/// Compile, reusing a previous result for identical source, arch and defines.
///
/// # Errors
///
/// As [`compile`].
pub fn compile_cached(
    source: &str,
    arch: (u32, u32),
    defines: &[(&str, String)],
) -> Result<String, NvrtcError> {
    let key = format!("{arch:?}|{defines:?}|{source}");
    if let Ok(guard) = CACHE.lock()
        && let Some(map) = guard.as_ref()
        && let Some(hit) = map.get(&key)
    {
        return Ok(hit.clone());
    }

    // Then the on-disk cache, which survives between runs.
    let path = disk_cache_path(cache_key(source, arch, defines));
    if let Some(ref p) = path
        && let Ok(ptx) = std::fs::read_to_string(p)
        && !ptx.is_empty()
    {
        if let Ok(mut guard) = CACHE.lock() {
            guard.get_or_insert_with(BTreeMap::new).insert(key, ptx.clone());
        }
        return Ok(ptx);
    }

    let ptx = compile(source, arch, defines)?;

    // Write through a temporary and rename, so a concurrent reader never sees a
    // half-written entry. A cache write that fails is not an error: the only
    // consequence is compiling again next time.
    if let Some(p) = path
        && let Some(dir) = p.parent()
        && std::fs::create_dir_all(dir).is_ok()
    {
        let tmp = p.with_extension(format!("tmp{}", std::process::id()));
        if std::fs::write(&tmp, &ptx).is_ok() {
            let _ = std::fs::rename(&tmp, &p);
        }
    }

    if let Ok(mut guard) = CACHE.lock() {
        guard.get_or_insert_with(BTreeMap::new).insert(key, ptx.clone());
    }
    Ok(ptx)
}

/// Why device source could not be compiled.
#[derive(Debug, Clone, thiserror::Error)]
pub enum NvrtcError {
    /// An `#include` named a file that is not part of the embedded sources.
    #[error("device source includes unknown header {name:?}; only the embedded headers resolve")]
    UnknownInclude {
        /// The unresolvable header name.
        name: String,
    },
    /// An `#include` line could not be read.
    #[error("malformed include directive: {line}")]
    MalformedInclude {
        /// The offending line.
        line: String,
    },
    /// NVRTC rejected the source.
    #[error("device compilation failed:\n{message}")]
    Compile {
        /// The NVRTC compiler log.
        message: String,
    },
}
